version: "3.8"

services:
  backend:
    build:
      context: .             # 현재 경로에 Dockerfile이 있어야 함
      dockerfile: Dockerfile # Dockerfile 이름 명시 (필요 시)
    container_name: portfolio-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
    networks:
      - app-network

networks:
  app-network:
    driver: bridge